apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-test
  name: devops-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-test
  strategy:
  template:
    metadata:
      labels:
        app: devops-test
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: devops-test
        matchLabelKeys:
        - pod-template-hash
      initContainers:
      - name: init-mysql
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup mysql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done"]
      containers:
      - image: devops-test
        imagePullPolicy: IfNotPresent
        name: devops-test
        env:
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mysql-root-password
                name: mysql
          - name: NODE_NAME
            value: "minikube-ara7788"
        ports:
          - containerPort: 8000
            name: http
            protocol: TCP
        resources:
          requests:
            cpu: 1
            memory: 1G
          limits:
            cpu: 2
            memory: 2G