apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: devops-test
  name: devops-test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: devops-test
  type: ClusterIP
